### ISSUE TITLE
Provide an array back listing the file actions and details.

### ISSUE THREAD

**Issue by rainabba** [MathieuLoutre/grunt-aws-s3#35]
I didn't see that this is available and admittedly haven't dug into code yet, but I wanted to get the ball rolling just in case because that output object would be very useful for other operations such as here: https://github.com/mllrsohn/grunt-invalidate-cloudfront/issues/9

Accepting  a callback or returning a promise that could be passed this object would be a great approach too.

**Comment by MathieuLoutre** [comment]
@rainabba Just to let you know this feature finally made it into the plugin. It now exports a variable on the grunt config with the list of changed files.

**Comment by rainabba** [comment]
Great timing for me as my work with S3 is going to resume as of about 2 hours ago so thanks!

**Comment by ianpogi5** [comment]
any examples on how to use aws_s3_changed in the gruntfile?

**Comment by MathieuLoutre** [comment]
Haven't used that personally, but you should be able to get what the list of files through `runt.config.get('aws_s3_changed')` and pass that onto an invalidation plugin.

**Comment by ianpogi5** [comment]
Is this what you mean?

```Gruntfule.js
invalidate_cloudfront: {
            options: {
                key: 'XXX',
                secret: 'XXX',
                distribution: 'xxx'
            },
            production: {
                files: grunt.config.get('aws_s3_changed')
            }
        }
```

**Comment by MathieuLoutre** [comment]
That's what I would try first, yes. Yet, I'm not sure what format grunt-invalidate-cloudfront expects for files, but it might just work. If not, you may have to map over the array of changed files and provide the changed files.

Additionally, you probably want to check that `grunt.config.get('aws_s3_changed')` isn't called at runtime but when invalidate cloudfront is called, otherwise there's every chance it'll be empty.

**Comment by ianpogi5** [comment]
Here's the error that I got
```
Running "invalidate_cloudfront:production" (invalidate_cloudfront) task
Invalidating 0 files: (none)

0 Completed and 0 In Progress invalidations on: XXX

Creating invalidation for 0 files
Fatal error: Your request contains one or more invalid invalidation paths.
```

Looks like it's empty. :-(

**Comment by pr1ntr** [comment]
so does this just not work?

**Comment by MathieuLoutre** [comment]
Well, in theory it should work, but in practice it might be hard to pass that info to another plugin if `grunt.config.get('aws_s3_changed')` is called at runtime, since that array is going to be empty until `grunt-aws-s3` finishes. Hope that makes sense. If you could stick a function in that `files` property, I'm pretty sure it would work.

**Comment by pr1ntr** [comment]
First thing i tried was
```
"files" : function () {
   return grunt.config.get('aws_s3_changed');
}
```

no dice :(

**Comment by MathieuLoutre** [comment]
As in, it crashes or it returns an empty array?
Can you log the time inside that function, just to make sure it's called _after_ the aws task has run?

**Comment by pr1ntr** [comment]
It's empty. I'll do my best a little later. Been really busy.

**Comment by MathieuLoutre** [comment]
Sure! Thanks for testing :)

**Comment by deargle** [comment]
Dropping a breadcrumb: dynamic loading solution [here](https://github.com/mllrsohn/grunt-invalidate-cloudfront/issues/9#issuecomment-276571383)
