### ISSUE TITLE
add deleteConcurrency

### ISSUE THREAD

**Issue by pr1ntr** [MathieuLoutre/grunt-aws-s3#83]
would be nice to be able to delete a lot of files at once. just sayin

**Comment by MathieuLoutre** [comment]
`delete` has a concurrency of a 1000 in fact. It deletes up to 1000 items in one fell swoop, and will do as many calls as necessary to delete all specified items. It's the fastest way to do it and I hardly see why you would want a lower concurrency. A higher one isn't possible because it's already at the max of AWS. Good thinking though! Maybe I should add this explanation to the docs?
